/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MarbleRouteImport } from './routes/marble'
import { Route as MosaicsRouteImport } from './routes/mosaics'
import { Route as TilesRouteImport } from './routes/tiles'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MarbleRoute = MarbleRouteImport.update({
  id: '/marble',
  path: '/marble',
  getParentRoute: () => rootRouteImport,
} as any)
const MosaicsRoute = MosaicsRouteImport.update({
  id: '/mosaics',
  path: '/mosaics',
  getParentRoute: () => rootRouteImport,
} as any)
const TilesRoute = TilesRouteImport.update({
  id: '/tiles',
  path: '/tiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/marble': typeof MarbleRoute
  '/mosaics': typeof MosaicsRoute
  '/tiles': typeof TilesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/marble': typeof MarbleRoute
  '/mosaics': typeof MosaicsRoute
  '/tiles': typeof TilesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/marble': typeof MarbleRoute
  '/mosaics': typeof MosaicsRoute
  '/tiles': typeof TilesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/marble'
    | '/mosaics'
    | '/tiles'
    | '/products/$slug'
    | '/rooms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/marble'
    | '/mosaics'
    | '/tiles'
    | '/products/$slug'
    | '/rooms/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/marble'
    | '/mosaics'
    | '/tiles'
    | '/products/$slug'
    | '/rooms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  MarbleRoute: typeof MarbleRoute
  MosaicsRoute: typeof MosaicsRoute
  TilesRoute: typeof TilesRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marble': {
      id: '/marble'
      path: '/marble'
      fullPath: '/marble'
      preLoaderRoute: typeof MarbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosaics': {
      id: '/mosaics'
      path: '/mosaics'
      fullPath: '/mosaics'
      preLoaderRoute: typeof MosaicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiles': {
      id: '/tiles'
      path: '/tiles'
      fullPath: '/tiles'
      preLoaderRoute: typeof TilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  MarbleRoute: MarbleRoute,
  MosaicsRoute: MosaicsRoute,
  TilesRoute: TilesRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  RoomsSlugRoute: RoomsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
